"""add_payment_method_pdf_filename_review_fields

Revision ID: b6e5cf2dd870
Revises: 63cbd409bfc6
Create Date: 2026-05-12 11:05:04.971143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e5cf2dd870'
down_revision: Union[str, None] = '63cbd409bfc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('pdf_filename', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('review_status', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('user_notes', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('exported_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'exported_at')
    op.drop_column('transactions', 'user_notes')
    op.drop_column('transactions', 'review_status')
    op.drop_column('transactions', 'pdf_filename')
    op.drop_column('transactions', 'payment_method')
    # ### end Alembic commands ###
